local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Image URL",
          name: "imageURL",
          widget: "string",
          required: true,
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          field: { label: "Image", name: "image", widget: "string" },
          required: false,
        }
      - {
          label: "Specifications",
          name: "specifications",
          widget: "text",
          required: true,
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Category 1", "Category 2", "Category 3"],
          required: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }

  - name: "updates"
    label: "Latest Updates"
    folder: "src/content/updates"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Image URL",
          name: "imageURL",
          widget: "string",
          required: true,
        }
      - {
          label: "Content",
          name: "content",
          widget: "markdown",
          required: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
